### ISSUE TITLE
Several packages are missing in requrements.txt

### ISSUE THREAD

**Issue by xandrd** [nasa/Kamodo#134]
Steps to reproduce 
```python
import kamodo_ccmc.readers.reader_utilities as RU
```
```
ModuleNotFoundError: No module named 's3fs'
```

**Comment by xandrd** [comment]
The following packages have to be included
s3fs
h5netcdf
netCDF4
boto3

**Comment by darrendezeeuw** [comment]
These four are already in the setup.cfg, so they don't need to be in requirements.txt. Any pip install of Kamodo will check that the packages in setup.cfg are also installed. I can't reproduce this error.

**Comment by xandrd** [comment]
This is true, if Kamodo is installed via pip, the dependencies will be handled via setup.cfg. However, if Kamodo is cloned directly from the repository, then requrements.txt helps with installation of the necessary packages in the virtual environment.

As far as I know, there is no command that allows you to install dependency from setup.cfg, like `pip install -r requirements.txt`, after the project was cloned. The requirements.txt is useful for development, which is why I suggest to include this small change.

**Comment by darrendezeeuw** [comment]
You can install dependencies for a cloned project. I do it all the time. If you are in the top directory of the cloned project, just type 'pip install .' and it installs the project and all dependencies.

**Comment by xandrd** [comment]
Thanks for the suggestion! This solution works with the console command, but require a bit extra work via IDE. I use PyCharm, which recognize requirements.txt by default. 

So, the problem is solvable on my end with a workaround. However, I still don't understand why not just add those packages in requirements.txt?

**Comment by darrendezeeuw** [comment]
I don't see a big negative to modifying requirements.txt this way, though its not how I've understood the intent of this file. I will accept and then slightly modify your PR.
