### ISSUE TITLE
Data extraction along a trajectory

### ISSUE THREAD

**Issue by darrendezeeuw** [nasa/Kamodo#15]
Data extraction along satellite trajectories is needed for many models to facilitate data/model comparisons of to probe local variability.  This should be a general use tool in Kamodo that makes use of each Kamodified model's interpolator.

**Comment by rebeccaringuette** [comment]
Completed for CTIPe, GITM, IRI, TIEGCM, and SWMF_IE. Others models either pending or in process. :)

**Comment by rebeccaringuette** [comment]
please close.
