### ISSUE TITLE
Depreciation warnings and missing dependency

### ISSUE THREAD

**Issue by rweigel** [nasa/Kamodo#20]
I was easily able to run the example at https://ccmc.gsfc.nasa.gov/Kamodo/notebooks/kameleon-kamodo/ but encountered two issues when using Python 3.8 (I meant to use Python 3.7)

First, I needed to `pip install execnet`

Second,

```
from kamodo.readers._kameleon_kamodo import Kameleon
```

results in about 20 of these warnings:

```
lib/python3.8/site-packages/sympy/physics/units/quantities.py:77: SymPyDeprecationWarning: 
Moving method to UnitSystem class has been deprecated since SymPy 1.5.
Use unit_system.set_quantity_dimension or
nanotesla.set_global_relative_scale_factor instead. See
https://github.com/sympy/sympy/issues/17765 for more info.
```

**Comment by rebeccaringuette** [comment]
This is addressed in kamodo-core. Please close.
