### ISSUE TITLE
SFcsv_reader leaving unclosed file

### ISSUE THREAD

**Issue by sapols** [nasa/Kamodo#75]
To avoid rerunning the `ModelFlythrough` function multiple times, I've been using the `SFcsv_reader` to read in the CSV file that gets output by `ModelFlythrough`. It seems that file is not getting closed after opening it. I get the warning:

```
/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:8: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/work/Output/ModelFlythrough/OpenGGCMFlythrough.csv' mode='r' encoding='UTF-8'>
```

I haven't looked at your other readers, but if this is happening with the CSV reader, it's likely happening with other readers too.

**Comment by rebeccaringuette** [comment]
Fixed in PR#80. Recommend closing issue.
