### ISSUE TITLE
Composability checking [feature]

### ISSUE THREAD

**Issue by asherp** [nasa/Kamodo#9]
Currently, Kamodo does not validate composed functions. Rather, it assumes function types are compatible already. A user cannot tell if their pipeline works until evaluation. It would be great if kamodo could test functions at composition time.

Proposed Solution:
At each step of a composition, call the composed function with default inputs and generate corresponding default outputs. For example:

```python
kamodo['f'] = kamodofy(lambda x = np.array([1,2,3]): x)
kamodo['g'] = kamodofy(lambda y = np.array([5,6,7]): y)
kamodo['h'] = 'f + g' 
```
kamodofy adds a data attribute to f and g by calling f and g without arguments. When 'h(x,y)' is composed from 'f' and 'g', kamodo should somehow assign its default arguments from f and g.

**Comment by rebeccaringuette** [comment]
This is addressed in kamodo-core.
